- .changeset/khaki-lions-glow.md
- packages/bundler-plugin-core/src/utils/logging.ts
Makes the grepping the logs in CI a little easier while debugging setups.
> ref(core): Add codecov prefix to log messages

- .changeset/four-houses-drive.md
- packages/bundler-plugin-core/src/utils/providers/Vercel.ts
- packages/bundler-plugin-core/src/utils/providers/__tests__/Vercel.test.ts
Vercel does not provide a whole slug that includes both the owner and repo so we need to create our own version of it.
> fix: Manually  create Git slug for Vercel

- .changeset/many-peas-repeat.md
- packages/bundler-plugin-core/src/bundle-analysis/bundleAnalysisPluginFactory.ts
- packages/bundler-plugin-core/src/utils/__tests__/uploadStats.test.ts
- packages/bundler-plugin-core/src/utils/uploadStats.ts
- log out status for failed responses
- add bundle name to success message
Main change is logging out `bundleName`, should hopefully make iteration speed quicker.
> ref(core): improve logging for upload stats

- .changeset/early-phones-prove.md
- packages/bundler-plugin-core/src/utils/providers/Vercel.ts
- packages/bundler-plugin-core/src/utils/providers/__tests__/Vercel.test.ts
Totally missed that Vercel does in fact have an env var that contains the branch name it's just labelled as `VERCEL_GIT_COMMIT_REF`
- Grab branch name from in Vercel helper from env
- Update tests
> fix: Support grabbing branch in Vercel

- .changeset/cool-sheep-care.md
- packages/bundler-plugin-core/build.config.ts
- packages/rollup-plugin/build.config.ts
- packages/vite-plugin/build.config.ts
- packages/webpack-plugin/build.config.ts
Small tweak to the build config to preserve the JSDoc comments as they were getting stripped out before.
> fix: Keep JSDoc comments in dts files

- .eslintrc.js
- .github/workflows/publish.yml
- package.json
- packages/bundler-plugin-core/package.json
- packages/bundler-plugin-core/src/types.ts
- packages/bundler-plugin-core/typedoc.json
- packages/rollup-plugin/package.json
- packages/rollup-plugin/src/index.ts
- packages/rollup-plugin/typedoc.json
- packages/vite-plugin/package.json
- packages/vite-plugin/src/index.ts
- packages/vite-plugin/typedoc.json
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/index.ts
- packages/webpack-plugin/typedoc.json
- pnpm-lock.yaml
- scripts/publish-docs.js
- typedoc.base.json
- typedoc.json
- typedoc/plugin-remove-references.js
This PR adds in the supporting foundation for using TypeDoc to auto generate docs for the bundler plugins, and eventually host them on gh-pages for this repo.
Closes #50 
- Add in `typedoc` dep
- Configure `typedoc`
- Add in supporting scripts and plugins
- Update comments to have types show up in TypeDoc
> feat: Auto gen type docs via TypeDoc

- README.md
- packages/bundler-plugin-core/README.md
- packages/rollup-plugin/README.md
- packages/vite-plugin/README.md
- packages/webpack-plugin/README.md
This PR updates the README's for the plugins to add in a disclaimer that they don't support coverage uploading, as well add in links to the new TypeDocs for config references.
> docs: Add in disclaimer in the plugin README's

- .changeset/popular-chicken-confess.md
- packages/bundler-plugin-core/src/bundle-analysis/__tests__/bundleAnalysisPluginFactory.test.ts
- packages/bundler-plugin-core/src/bundle-analysis/bundleAnalysisPluginFactory.ts
- packages/bundler-plugin-core/src/types.ts
- packages/bundler-plugin-core/src/utils/__tests__/normalizeOptions.test.ts
- packages/bundler-plugin-core/src/utils/normalizeOptions.ts
- packages/bundler-plugin-core/src/utils/providers/GitHubActions.ts
- packages/rollup-plugin/src/rollup-bundle-analysis/__tests__/rollupBundleAnalysisPlugin.test.ts
- packages/vite-plugin/src/vite-bundle-analysis/__tests__/viteBundleAnalysisPlugin.test.ts
- packages/webpack-plugin/src/webpack-bundle-analysis/__tests__/webpackBundleAnalysisPlugin.test.ts
Add in `debug` option to plugin configs, as well when `debug` is `true` log out the short sha.
> feat: Add in debug option, and log out short sha for commit being uploaded

- integration-tests/test-api/src/index.ts
Ran into some issues with handling duplicate bundle names, so this PR fixes that by creating primary keys off of the `id` and `bundle_name` columns, and also requiring the ID when grabbing details by bundle name. (basically all server builds for nuxt were esm soooo that didn't work just using the bundle name)
> fix: Small tweak to table and endpoint in integration test-api

- .changeset/two-spies-talk.md
- integration-tests/fixtures/generate-bundle-stats/nuxt/nuxt-plugin.test.ts
- integration-tests/fixtures/generate-bundle-stats/rollup/rollup-plugin.test.ts
- integration-tests/fixtures/generate-bundle-stats/sveltekit/sveltekit-plugin.test.ts
- integration-tests/fixtures/generate-bundle-stats/vite/vite-plugin.test.ts
- integration-tests/fixtures/generate-bundle-stats/webpack/webpack-plugin.test.ts
- integration-tests/scripts/gen-config.ts
- packages/bundler-plugin-core/src/index.ts
- packages/bundler-plugin-core/src/utils/__tests__/normalizeOptions.test.ts
- packages/bundler-plugin-core/src/utils/normalizeOptions.ts
- packages/nuxt-plugin/src/index.ts
- packages/rollup-plugin/src/index.ts
- packages/sveltekit-plugin/src/index.ts
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/index.ts
This PR updates the plugins to hard fail when a user passes an invalid bundle name, exiting the process. This is a small change, but should really help people when setting up the bundler plugins if they're not getting any data in Codecov but still seeing checkmarks across their CI.
Closes #124
- Add in new `handleErrors` function the plugin core
- Use new function in the various plugins
- Add in integration tests
> feat: Hard fail on invalid bundle names

- .github/workflows/ci.yml
- examples/nuxt/nuxt.config.ts
- examples/sveltekit/vite.config.ts
Welp forgot to remove these `dryRun` settings in the Nuxt, and SvelteKit example apps, this PR just removes those and actually uploads the stats.
> build: Upload Nuxt and SvelteKit example stats

- .github/workflows/ci.yml
- examples/next-js/next.config.js
- examples/nuxt/nuxt.config.ts
- examples/remix/vite.config.ts
- examples/rollup/rollup.config.js
- examples/sveltekit/vite.config.ts
- examples/vite/vite.config.ts
- examples/webpack/webpack.config.js
- packages/bundler-plugin-core/src/types.ts
- packages/bundler-plugin-core/src/utils/__tests__/normalizeOptions.test.ts
- packages/bundler-plugin-core/src/utils/normalizeOptions.ts
- packages/bundler-plugin-core/src/utils/preProcessBody.ts
- packages/bundler-plugin-core/src/utils/providers/GitHubActions.ts
- packages/bundler-plugin-core/src/utils/providers/__tests__/GitHubActions.test.ts
This PR updates the GitHubAction provider to grab the correct "compare SHA" for GH PRs and send it along to the API. This value has also been added to the upload override options so the user can override the value in their bundler config if they wish to do so.
- Add `compareSha` to `normalizeOptions`
- Update types
- Update `GitHubActions` provider utils
- Update examples to have `debug` set to `true`
- Small fixes to CI action versions
> feat: Grab compare SHA for GH pre-merge commits

- .changeset/warm-moles-float.md
- packages/bundler-plugin-core/package.json
- packages/bundler-plugin-core/src/utils/providers/GitHubActions.ts
- packages/bundler-plugin-core/src/utils/providers/__tests__/GitHubActions.test.ts
- pnpm-lock.yaml
GitHub provides a package called `@actions/github` which should allow us to grab the payload context and pass it to Codecov without the need to increase the checkout fetch-depth or override the value in the action yaml.
Closes codecov/engineering-team#2207
- Introduce `@actions/github`
- Refactor SHA and Compare SHA GHA functions to use PR payload from `@actions/GitHub`
- Update tests
> ref: GHA provider to use @actions/github

- .changeset/pre.json
- .changeset/shiny-ghosts-play.md
This PR sets everything up for the `1.0.0` release of the plugins, adding in a major release as well as exiting pre-mode. Here is an example after running `prepare-publish` ensuring that everything is working as expected with changeset: https://github.com/codecov/codecov-javascript-bundler-plugins/pull/165
- codecov/engineering-team#2440
- codecov/engineering-team#2441
> chore: Align Change Sets for 1.0.0 release

- .changeset/moody-camels-accept.md
- packages/bundler-plugin-core/src/utils/Output.ts
- packages/bundler-plugin-core/src/utils/__tests__/Output.test.ts
- packages/bundler-plugin-core/src/utils/__tests__/getPreSignedURL.test.ts
- packages/bundler-plugin-core/src/utils/__tests__/uploadStats.test.ts
- packages/bundler-plugin-core/src/utils/getPreSignedURL.ts
- packages/bundler-plugin-core/src/utils/uploadStats.ts
This PR introduces some small tweaks to enable better debug-ability of the plugins, by expanding on the error messages and introducing some new debug logs.
- Add debug logs with error for getting pre-signed url and uploading stats
- Update bad response logs with more details
> chore: Add in new debug logs, and expand on current logs

- .changeset/strong-readers-count.md
- codecov.yml
- integration-tests/fixtures/generate-bundle-stats/rollup/__snapshots__/rollup-plugin.test.ts.snap
- integration-tests/fixtures/generate-bundle-stats/vite/__snapshots__/vite-plugin.test.ts.snap
- integration-tests/fixtures/generate-bundle-stats/webpack/__snapshots__/webpack-plugin.test.ts.snap
- packages/bundler-plugin-core/src/utils/__tests__/normalizePath.test.ts
- packages/bundler-plugin-core/src/utils/normalizePath.ts
We're currently unable to handle normalizing strings when hashes have a custom length set `[hash:16]` for example. This PR resolves this issue by searching for the `]` character after finding the starting hash string match.
- Update `normalizePath` to handle custom hash lengths
- Update tests
> fix: Issue when hash length is set

- .changeset/serious-olives-add.md
- examples/bundle-analyzer-cli/package.json
- examples/bundle-analyzer-lib-cjs/analyze.js
- examples/bundle-analyzer-lib-esm/analyze.ts
- packages/bundler-plugin-core/src/utils/fetchWithRetry.ts
- packages/bundler-plugin-core/src/utils/getPreSignedURL.ts
- packages/bundler-plugin-core/src/utils/providers/AppVeyorCI.ts
- packages/bundler-plugin-core/src/utils/providers/AzurePipelines.ts
- packages/bundler-plugin-core/src/utils/providers/Bitbucket.ts
- packages/bundler-plugin-core/src/utils/providers/Bitrise.ts
- packages/bundler-plugin-core/src/utils/providers/Buildkite.ts
- packages/bundler-plugin-core/src/utils/providers/CircleCI.ts
- packages/bundler-plugin-core/src/utils/providers/Cirrus.ts
- packages/bundler-plugin-core/src/utils/providers/CloudflarePages.ts
- packages/bundler-plugin-core/src/utils/providers/CodeBuild.ts
- packages/bundler-plugin-core/src/utils/providers/Drone.ts
- packages/bundler-plugin-core/src/utils/providers/GitHubActions.ts
- packages/bundler-plugin-core/src/utils/providers/GitLabCI.ts
- packages/bundler-plugin-core/src/utils/providers/HerokuCI.ts
- packages/bundler-plugin-core/src/utils/providers/JenkinsCI.ts
- packages/bundler-plugin-core/src/utils/providers/Local.ts
- packages/bundler-plugin-core/src/utils/providers/Netlify.ts
- packages/bundler-plugin-core/src/utils/providers/Render.ts
- packages/bundler-plugin-core/src/utils/providers/TeamCity.ts
- packages/bundler-plugin-core/src/utils/providers/TravisCI.ts
- packages/bundler-plugin-core/src/utils/providers/Vercel.ts
- packages/bundler-plugin-core/src/utils/providers/Wercker.ts
- packages/bundler-plugin-core/src/utils/providers/Woodpecker.ts
- packages/bundler-plugin-core/src/utils/providers/__tests__/AppVeyorCI.test.ts
- packages/bundler-plugin-core/src/utils/providers/__tests__/Local.test.ts
This PR adds debug logging to each provider on all the different getter functions so that we can provide a better debugging experience for users.
- Update all providers to debug log all upload params when debug is enabled
> chore: Add in debug logs for all upload params

- .changeset/moody-goats-sing.md
- examples/next-js/package.json
- integration-tests/test-apps/nextjs/package.json
- packages/nextjs-webpack-plugin/package.json
- pnpm-lock.yaml
Bump version of `next` to resolve vulnerabilities
* 14.2.10
* 13.5.7
Closes https://github.com/codecov/internal-issues/issues/929
Closes https://github.com/codecov/internal-issues/issues/935
Due 11/18/24
> chore: Resolve nextjs vuln

- .changeset/brave-bikes-wait.md
- examples/bundle-analyzer-cli/package.json
- examples/oidc/package.json
- examples/rollup/package.json
- examples/tokenless/package.json
- examples/vite/package.json
- integration-tests/fixtures/generate-bundle-stats/nuxt/__snapshots__/nuxt-plugin.test.ts.snap
- integration-tests/fixtures/generate-bundle-stats/remix/__snapshots__/remix-plugin.test.ts.snap
- integration-tests/fixtures/generate-bundle-stats/rollup/__snapshots__/rollup-plugin.test.ts.snap
- integration-tests/fixtures/generate-bundle-stats/sveltekit/__snapshots__/sveltekit-plugin.test.ts.snap
- integration-tests/fixtures/generate-bundle-stats/vite/__snapshots__/vite-plugin.test.ts.snap
- integration-tests/package.json
- packages/rollup-plugin/package.json
- packages/rollup-plugin/vitest.config.ts
- pnpm-lock.yaml
Resolve vulnerability in rollup (resolved versions - 4.22.4, 3.29.5)
Closes https://github.com/codecov/internal-issues/issues/931
> chore: Resolve rollup vuln

- .changeset/neat-jobs-train.md
- packages/bundler-plugin-core/src/utils/Output.ts
- packages/bundler-plugin-core/src/utils/__tests__/Output.test.ts
- packages/nextjs-webpack-plugin/src/nextjs-webpack-bundle-analysis/nextJSWebpackBundleAnalysisPlugin.ts
- packages/rollup-plugin/src/rollup-bundle-analysis/rollupBundleAnalysisPlugin.ts
- packages/vite-plugin/src/vite-bundle-analysis/viteBundleAnalysisPlugin.ts
- packages/webpack-plugin/src/webpack-bundle-analysis/webpackBundleAnalysisPlugin.ts
We noticed that when running the plugins to analyze the plugins the bundle names were not being reset with Unbuild correctly. This resolves the issue, by reseting the bundle name when running.
> fix: Bundle names not being reset properly

- examples/webpack/package.json
- integration-tests/fixtures/generate-bundle-stats/webpack/__snapshots__/webpack-plugin.test.ts.snap
- packages/nextjs-webpack-plugin/package.json
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/webpack-bundle-analysis/utils/__tests__/processChunks.test.ts
- pnpm-lock.yaml
Update Webpack versions, since they're only dev deps, not including a changelog.
> chore: Update Webpack versions

- .changeset/rare-foxes-cheat.md
- packages/bundler-plugin-core/src/utils/normalizePath.ts
Quick PR to remove an unused regex escape char in `normalizePath` function.
> fix: Remove unused regex escape char

- .github/workflows/ci.yml
Looks like we haven't been pointing some of our example builds to staging, this resolves this issue by setting the correct token and api endpoints
> build: Point example uploads to staging

- .eslintrc.js
- .github/workflows/ci.yml
- .gitignore
- typedoc.json
- typedoc/plugin-remove-references.mjs
When updating the dependences in the previous PR I missed checking to see if the typedocs would still build, this PR resolves an issue with how they are being built. I've also added in a CI step to check to see if we're able to build the docs.
- Refactor plugin to ESM
- Update references
- Add in CI step to check if docs are able to be built
> fix: Issue with building Typedocs

- packages/bundler-plugin-core/src/utils/Output.ts
- packages/bundler-plugin-core/src/utils/getPreSignedURL.ts
- packages/bundler-plugin-core/src/utils/normalizeOptions.ts
- packages/bundler-plugin-core/src/utils/uploadStats.ts
This PR adds in some extra tracing that's a bit finer grain looking at the specific fetch requests for getting the pre-signed URL, and uploading stats. As well we've added in distributed tracing for getting the pre-signed URL (only when talking to Codecov).
Ticket: codecov/engineering-team#954
- Add tracing around `getPreSignedURL`, and `uploadStats` fetching
> feat: Add finer Sentry HTTP Tracing

- .changeset/slimy-ducks-double.md
- integration-tests/package.json
- pnpm-lock.yaml
This PR removes the `solid-start` package from the integration tests, to remove a child dep we're not using. I added in a changeset because of the shared lockfile and the potential downstream that something else may be updated in a package.
- Removed `solid-start` package
- Moved dev package to the `devDependencies` section
- Update lockfile
> chore: Remove unused solid-start package

- packages/bundler-plugin-core/package.json
- packages/bundler-plugin-core/src/utils/providers/GitHubActions.ts
- packages/bundler-plugin-core/src/utils/providers/__tests__/GitHubActions.test.ts
- pnpm-lock.yaml
- also added checks for the merge group event just in case
- also `@octokit/webhook-definitions` was deprecated so i changed it to use `@octokit/webhook-types` (which has the definition for the MergeGroupEvent)
> fix: typo affecting commit and compareSHA

- .changeset/witty-icons-appear.md
- examples/next-js/package.json
- integration-tests/test-apps/nextjs/package.json
- pnpm-lock.yaml
Bump `next` to 14.2.25
fixes https://github.com/codecov/codecov-javascript-bundler-plugins/security/dependabot/131
fixes https://github.com/codecov/codecov-javascript-bundler-plugins/security/dependabot/129
fixes https://github.com/codecov/codecov-javascript-bundler-plugins/security/dependabot/116
fixes https://github.com/codecov/codecov-javascript-bundler-plugins/security/dependabot/103
fixes https://github.com/codecov/codecov-javascript-bundler-plugins/security/dependabot/102
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all …
> chore(security): bump next to 14.2.25
